# Generated by Django 6.0.4 on 2026-05-01 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'support categories',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='SupportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('faq', 'FAQ'), ('policy', 'Policy'), ('guide', 'Guide'), ('shipping', 'Shipping Info')], default='faq', max_length=20)),
                ('question', models.TextField(blank=True, help_text='For FAQ entries: the triggering question. For policies: leave blank.')),
                ('content', models.TextField(help_text='The answer / policy body. Keep focused — one topic per record.')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords to boost retrieval accuracy.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('embedding_id', models.IntegerField(blank=True, null=True)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.supportcategory')),
            ],
            options={
                'indexes': [models.Index(fields=['doc_type', 'is_active'], name='support_sup_doc_typ_8a4a2e_idx')],
            },
        ),
    ]
